Hopla webinterface
CenterForMedicalGeneticsGhent/Hopla pull request #11
Opened 2022-02-17 11:03 UTC by janvandenschilden

2022-02-17 11:03 UTC, janvandenschilden commented
laatste tabje moet nog worden afgewerkt. De rest is klaar.

2022-02-17 11:08 UTC, matthdsm commented
Kan je de originele structuur van de repo herstellen. Deze wordt gebruikt voor de conda recipe

2022-02-17 13:00 UTC, janvandenschilden commented
Is de structuur nu goed?

2022-02-18 07:49 UTC, matthdsm commented
Yes, looks good!

2022-02-23 13:48 UTC, matthdsm commented
@janvandenschilden, je hoeft je code niet te clonen in je dockerfile, je kan deze toevoegen met het `ADD` keyword
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

2022-02-23 14:17 UTC, janvandenschilden commented
> @janvandenschilden, je hoeft je code niet te clonen in je dockerfile, je kan deze toevoegen met het `ADD` keyword https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

Dankje voor de tip, ik heb het aangepast. 
De docker zou nu klaar moeten zijn. 
Kan je die op de server kunnen zetten en linken aan een URL zodat coPGTM de UI kunnen beginnen gebruiken?

2022-02-23 14:21 UTC, matthdsm commented
ping @tomiles

2022-02-24 07:32 UTC, matthdsm commented on Dockerfile
> +RUN yarn install
Do we need a `yarn build` to compile for production? cfr your manual

2022-02-24 07:45 UTC, matthdsm commented on UI/package.json
> +  "name": "frontend",
Ik zou je app een meer descriptive naam geven e.g. hopla-ui of simpelweg hopla

2022-02-24 07:46 UTC, matthdsm commented on UI/src/components/Inputs/InputFileCytoband.vue
> +    label="Cytband file absolute path"
typo -> Cytoband

2022-02-24 08:32 UTC, tomiles commented
@janvandenschilden did you check that the included image assets have a proper license to be able to be use in this project?

2022-02-24 08:55 UTC, tomiles commented
Do we need to commit the generateConfigFromExcel files?

2022-02-24 09:44 UTC, tomiles requested changes

2022-02-24 09:44 UTC, tomiles commented on Dockerfile
> +ADD ./ /home/node/Hopla/
Best to move your Dockerfile to the UI subdirectory, and use a .dockerignore file to avoid unneeded files being build into the image.

2022-02-24 09:44 UTC, tomiles commented on README_DOCKER.md
> +docker build --no-cache -t hopla ./
best to remove the `--no-cache`

2022-02-24 09:44 UTC, tomiles commented on Dockerfile
> +RUN yarn install
Or make it a 2 stage image build, first compile and minify. Then add those products (without the yarn/build dependencies into a more minimal 'runtime' image.

2022-02-24 09:44 UTC, tomiles commented on UI/src/components/Inputs/InputInheritance.vue
> +                'XLR',
Maybe a bit clearer to not to use abbreviations for the display values in the UI form (you can still use the abbreviated coding as the actual value behind the scenes)

2022-02-24 09:44 UTC, tomiles commented on UI/src/components/Inputs/InputRegion.vue
> +        }
Might be good to validate if the region is a valid region: check if integer (don't want negative or floating point numbers), end > start position ...

2022-02-24 09:44 UTC, tomiles commented on UI/src/components/Parsers/ParseSectionMandatoryTitle.vue
> +                "# OPGELET, DIT MOET EEN FILE ZIJN, GEEN MAP NAAM"
remove dutch remark

2022-02-24 10:00 UTC, janvandenschilden commented
> license

I used flaticon free icons 
https://www.flaticon.com

2022-02-24 12:05 UTC, matthdsm commented on Dockerfile
> +RUN yarn install
fixed with 2 stage build, image size shrunk from 1.3GB to 25mb

2022-02-24 12:05 UTC, matthdsm commented on UI/package.json
> +  "name": "frontend",
fixed

2022-02-24 12:05 UTC, matthdsm commented on Dockerfile
> +ADD ./ /home/node/Hopla/
fixed

2022-02-24 12:05 UTC, matthdsm commented on README_DOCKER.md
> +docker build --no-cache -t hopla ./
fixed

2022-02-24 12:07 UTC, matthdsm commented
@janvandenschilden, ik heb alle docker issues opgelost. Als jij nog kijkt om de andere comments op te lossen zijn we er denk ik.

2022-02-24 13:37 UTC, janvandenschilden commented
> @janvandenschilden, ik heb alle docker issues opgelost. Als jij nog kijkt om de andere comments op te lossen zijn we er denk ik.

Dankjewel voor alle feedback en docker issues op te lossen! 
Ik ben ondertussen bezig met de andere issues op te lossen.

2022-02-24 15:26 UTC, janvandenschilden commented on UI/src/components/Inputs/InputInheritance.vue
> +                'XLR',
This was discussed, but apparently the abbreviations are very well known and preferred.

2022-02-24 15:26 UTC, janvandenschilden commented
I fixed all the issues. Should be good to go for the merge. 
Thanks again for the feedback

2022-02-25 06:45 UTC, matthdsm commented
looks OK to me,
@tomiles?

2022-02-28 14:57 UTC, janvandenschilden commented
@tomiles, do you think it is okay like this?

2022-02-28 16:33 UTC, tomiles commented on UI/src/components/Inputs/InputRegion.vue
> +        }
is hier iets voor aangepast? zie heel wat extra checks voor _old_ versus _new_ values maar nergens een controle voor een geldige region

2022-03-07 13:07 UTC, tomiles commented
@janvandenschilden kan je eens verduidelijken wat het status van de UI nu is? zie hier constant veel veranderingen gebeuren en massa's commits binnenkomen. Zo kan ik dit niet bijhouden om te reviewen

2022-03-07 15:43 UTC, janvandenschilden commented
> @janvandenschilden kan je eens verduidelijken wat het status van de UI nu is? zie hier constant veel veranderingen gebeuren en massa's commits binnenkomen. Zo kan ik dit niet bijhouden om te reviewen

De versie sinds 24 februari is klaar voor productie. Dit is niet de finale versie, maar wel een upgrade ten opzichte van handmatig config files op te stellen. De CoPGTM wou zo snel mogelijk dit al beginnen gebruiken, maar heeft ook feedback gegeven voor verbeteringen, aanpassingen en enkele feature requests. Deze ben ik systematisch aan het toevoegen en telkens ik een werkend geheel heb aan het pushen naar de main branch. Doordat de pull request nog open staat zie jij die updates.

2022-03-07 15:59 UTC, tomiles commented
Dat is de reden dat je een pull request vanaf een branch doet en niet je main/master. nu is deze PR een kluwen van tijdelijk en afgewerkt werk door elkaar met elke merge van je dv naar main. Je maakt een branch per "brok" werk die samen hoort, zodat er overzicht is. Heb je onder tussen ngo ander werk, dan doe je dat in een afzonderlijke branch. Nu kan ik op basis van deze PR niet meer uitmaken wat nu de code is die "klaar" is om naar productie te gaan en te merken in de project repo  "main" branch.

2022-03-08 13:37 UTC, tomiles approved these changes

2022-03-08 13:38 UTC, matthdsm approved these changes

2022-03-08 13:38 UTC, merged